# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RuneEdit < Formula
  desc "TUI markdown editor"
  homepage "https://github.com/aka-rider/rune"
  version "1.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/aka-rider/rune/releases/download/v1.0.1/rune-darwin-arm64.tar.gz"
    sha256 "3cd307d61b9740d271ce40fe740d4f2a6fc49accb78296cd9b3e2bf63e0a2bf9"

    define_method(:install) do
      bin.install "rune"
    end
  end

  test do
    system "#{bin}/rune", "--version"
  end
end
