# This file was generated by GoReleaser. DO NOT EDIT.
cask "leash" do
  version "1.0.0"

  on_macos do
    sha256 "8001e29114f03b9726afce14ed9dfe024d78d972115f98143785ef1bc8edee63"
    url "https://github.com/aka-rider/leash/releases/download/v#{version}/leash_#{version}_darwin_universal.tar.gz",
        verified: "github.com/aka-rider/leash"
  end

  name "leash"
  desc "Transparent macOS seatbelt sandbox for any command"
  homepage "https://github.com/aka-rider/leash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leash"
  binary "leash-trace"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
