# This file was generated by GoReleaser. DO NOT EDIT.
cask "leash" do
  version "1.0.0"

  on_macos do
    sha256 "f295cd8372c0cfa5123a2223f15f085188a5bca9e1ec05246e8585437960a28d"
    url "https://github.com/aka-rider/leash/releases/download/v#{version}/leash_#{version}_darwin_universal.tar.gz"
  end

  name "leash"
  desc "Transparent macOS seatbelt sandbox for any command"
  homepage "https://github.com/aka-rider/leash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leash"
  binary "leash-trace"

  # No zap stanza required

end
