# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune-edit" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "c2528e0b3692730d2db74bf765d4cd52fbd28c9cbd8b678c1f4d2baced75e920"
      url "https://github.com/aka-rider/rune/releases/download/v#{version}/rune-darwin-arm64.tar.gz",
        verified: "github.com/aka-rider/rune"
    end
  end

  name "rune-edit"
  desc "TUI markdown editor"
  homepage "https://github.com/aka-rider/rune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"

  # No zap stanza required

end
