# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune-edit" do
  version "1.1.1"

  on_macos do
    on_arm do
      sha256 "212c6674b70f02a6a91c2c452b8139aa58221c1ec938c95e05decd5d8ffbe8f1"
      url "https://github.com/aka-rider/rune/releases/download/v#{version}/rune-darwin-arm64.tar.gz",
        verified: "github.com/aka-rider/rune"
    end
  end

  name "rune-edit"
  desc "TUI markdown editor"
  homepage "https://github.com/aka-rider/rune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rune"]
    end
  end

  # No zap stanza required

end
