# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune-edit" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "5fbb1b826d545bed5813c4eabec0ae195b7fdaeaeeaa49cab47ffe5420b292a9"
      url "https://github.com/aka-rider/rune/releases/download/v#{version}/rune-darwin-arm64.tar.gz",
        verified: "github.com/aka-rider/rune"
    end
  end

  name "rune-edit"
  desc "TUI markdown editor"
  homepage "https://github.com/aka-rider/rune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rune"]
    end
  end

end
